//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonCT
    {
        public int MaHDCT { get; set; }
        public int MaSach { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
        public double GiaKM { get; set; }
        public int MaHD { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
