//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMaiCT
    {
        public int MaKMCT { get; set; }
        public int MaSach { get; set; }
        public double DonGiaKM { get; set; }
        public int MaKM { get; set; }
    
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
